name = "AVTM - Cruel World"
author = "rasec"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f1416b961109dddb89f98f88c24563fac61692f695194e2e1a1288b9f376fc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
